version: '3'

tasks:
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  build:
    cmds:
      - docker compose up -d --build server
  redis:
    cmds:
      - docker compose up -d redis
  logs:
    aliases:
      - log
    cmds:
      - docker compose logs -f
  logs:server:
    aliases:
      - log:server
    cmds:
      - docker compose logs -f server
  db:
    cmds:
      - docker compose exec db mysql -u root -pexample
  lint:
    cmds:
      - buf lint
      - buf format -w
